#pragma once

#define FRAMES 60


#define PACMAN_SPEED 300

// pixels a second
#define CHASER_CHASE_SPEED 180
#define AMBUSHER_CHASE_SPEED 180
#define FICKLE_CHASE_SPEED 180
#define STUPID_CHASE_SPEED 180

#define CHASER_FRIGHTENED_SPEED 120
#define AMBUSHER_FRIGHTENED_SPEED  120
#define FICKLE_FRIGHTENED_SPEED  120
#define STUPID_FRIGHTENED_SPEED  120

#define GHOST_EATEN_SPEED 300