
#ifndef SPEEDS
#define SPEEDS

#define PACMAN_STEP_SIZE 2 

#define CHASER_CHASE_STEP_SIZE 1
#define AMBUSHER_CHASE_STEP_SIZE 1
#define FICKLE_CHASE_STEP_SIZE 1
#define STUPID_CHASE_STEP_SIZE 1

#define CHASER_FRIGHTENED_STEP_SIZE 1
#define AMBUSHER_FRIGHTENED_STEP_SIZE  1
#define FICKLE_FRIGHTENED_STEP_SIZE  1
#define STUPID_FRIGHTENED_STEP_SIZE  1

#endif
