
#ifndef SPEEDS
#define SPEEDS

#define PACMAN_STEP_SIZE 2

#define CHASER_CHASE_STEP_SIZE PACMAN_STEP_SIZE * 0.9375
#define AMBUSHER_CHASE_STEP_SIZE PACMAN_STEP_SIZE * 0.625
#define FICKLE_CHASE_STEP_SIZE PACMAN_STEP_SIZE * 0.625
#define STUPID_CHASE_STEP_SIZE PACMAN_STEP_SIZE * 0.625

#define CHASER_FRIGHTENED_STEP_SIZE CHASER_CHASE_STEP_SIZE / 2
#define AMBUSHER_FRIGHTENED_STEP_SIZE AMBUSHER_CHASE_STEP_SIZE / 2
#define FICKLE_FRIGHTENED_STEP_SIZE FICKLE_CHASE_STEP_SIZE / 2
#define STUPID_FRIGHTENED_STEP_SIZE STUPID_CHASE_STEP_SIZE / 2





#endif